Allow adding secondary email authenticator without verification
authgear/authgear-server pull request #2828
Opened 2023-01-18 04:19 UTC by IniZio

ref: #2748 

based on: #2802

2023-01-30 03:56 UTC, carmenlau requested changes

2023-01-30 06:21 UTC, IniZio commented
- [ ] Create verified claim if not exist on login

2023-01-31 08:21 UTC, IniZio commented on pkg/lib/authn/authenticator/password_authenticator.go
> +		MarkVerified: true,
The flag has some extra conditions depending on previous node e.g. is new user, so probably cannot just derive from config. 

I updated to pass through node field instead, see if would be better? 🙏

2023-02-01 03:40 UTC, IniZio commented
TBC, but the specific use case might use custom flow instead. Will probably only need "Create verified claim on auth end".

2023-02-01 06:46 UTC, closed without merging