Add unknown label for empty device column in sessions table
authgear/authgear-server pull request #4151
Opened 2024-04-22 07:26 UTC by IniZio

ref #4139 / DEV-1228

![image](https://github.com/authgear/authgear-server/assets/3119725/214beff3-b9d3-4b32-bb10-0c34e08d825a)

2024-04-22 10:17 UTC, IniZio commented
Updated to now show raw user agent in authui setting page.

2024-04-23 03:37 UTC, louischan-oursky requested changes

2024-04-23 04:14 UTC, IniZio commented on pkg/admin/graphql/session.go
> +				Type: graphql.NewNonNull(graphql.String),
Updated to be nullable.

2024-04-23 06:29 UTC, louischan-oursky approved these changes

2024-04-23 06:30 UTC, merged