[DEPS: #4476] Implement captcha modal in AuthUI v2
authgear/authgear-server pull request #4477
Opened 2024-07-18 18:04 UTC by pkong-ds

## What's in this PR?
Implement captcha guard in
- [ ] signup flow
  - [x] identify
    - [x] loginid
    - [x] oauth
  - [ ] create_authenticator
    - [ ] password
    - [ ] oobotp
    - [ ] totp
- [x] promote flow
  - [x] identify
    - [x] loginid
    - [x] oauth
  - [ ] create_authenticator (handled in signupflow > create_authenticator)
- [x] login flow
  - [x] identify
    - [x] loginid
    - [x] oauth
    - [x] passkey
  - [x] authenticate
    - [x] password
    - [x] passkey
    - [x] oobotp
    - [x] totp
    - [x] recoverycode
- [x] signup_login flow
  - [x] switch flow success
  - [x] identify
    - [x] loginid
    - [x] oauth
    - [x] passkey
- [x] reauth flow
  - [x] authentication
    - [x] password
    - [x] passkey
    - [x] oobotp
    - [x] totp
- [x] account_recovery_flow
  - [x] identify

2024-07-18 18:21 UTC, pkong-ds commented
To make this PR smaller, maybe we can do one PR for each flow type/step. i.e.

PR 1 - login identify
PR 2 - login authentication
PR 3 - signup identify 
...

See what daic prefer 🙏

2024-07-19 12:09 UTC, pkong-ds commented
Added fade-in fade-out

https://github.com/user-attachments/assets/029dc7b9-5683-42df-a9c3-62bbab6da4ae

2024-07-30 17:19 UTC, pkong-ds commented
This PR feature logic is complete. pending modal design and animation. Suggest review first 🙏

2024-08-01 08:03 UTC, louischan-oursky requested changes

2024-08-01 08:03 UTC, louischan-oursky commented on resources/authgear/templates/en/web/authflowv2/login.html
> +      {{ if (or (and $show_phone_input $show_captcha_phone) (and $show_text_input (or $show_captcha_email $show_captcha_username)))}}
The condition can be simplified into `if (or $show_captcha_phone $show_captcha_email $show_captcha_username)`.

Rationale: You have checked `$show_phone_input` or `$show_text_input` when you set `$show_captcha_*` to true. So `(and $show_phone_input $show_captcha_*` is redundant.

2024-08-05 01:08 UTC, pkong-ds commented
@louischan-oursky updated, thanks!

2024-08-05 05:36 UTC, louischan-oursky approved these changes

2024-08-05 05:37 UTC, merged