Allow captcha configuration in signup create_authenticator oob_otp
authgear/authgear-server pull request #4508
Opened 2024-07-29 15:49 UTC by pkong-ds

2024-08-01 06:18 UTC, louischan-oursky requested changes
mark this as Request changes.

2024-08-05 01:11 UTC, pkong-ds commented
Seems this conflicts with #4512 if I change e2e tests in both PRs. Lemme make this depends on #4512

2024-08-06 07:20 UTC, pkong-ds commented
@louischan-oursky in case you missed, this is ready for review 🙏

2024-08-06 12:39 UTC, louischan-oursky approved these changes

2024-08-06 12:51 UTC, merged