Allow configuring captcha by custom flow
authgear/authgear-server pull request #4512
Opened 2024-07-30 07:48 UTC by pkong-ds

ref dev-1606

Allow below configuration

```
bot_protection:
  authentication_flow:
    signup_or_login:
      mode: never
    account_recovery:
      mode: always
  authenticator:
    password:
      mode: never
    oob_otp_email:
      mode: always
    oob_otp_sms:
      mode: always
```

2024-07-30 08:49 UTC, pkong-ds commented
@tung2744 Can help review (and merge) this PR? 🙇 Seems daic too many PRs already :sadfrog:

2024-07-30 08:58 UTC, louischan-oursky commented
Let me review this. @tung2744 please review https://github.com/authgear/authgear-server/pull/4505 for me

2024-07-31 13:17 UTC, pkong-ds commented
Also added new generated flows

2024-08-02 04:21 UTC, louischan-oursky commented
The e2e test failed.

2024-08-02 04:21 UTC, louischan-oursky requested changes
The e2e tests failed.

2024-08-05 01:24 UTC, pkong-ds commented
@louischan-oursky e2e tests pass locally now, thanks!

2024-08-05 04:10 UTC, louischan-oursky approved these changes

2024-08-05 04:10 UTC, louischan-oursky commented on pkg/lib/config/testdata/bot_protection_tests.yaml
> +      mode: invalid_mode
Please keep the newline at the end of the file. Configure your text editor to do this for text files.

2024-08-05 04:19 UTC, merged