Implement ldap configuration
authgear/authgear-server pull request #4520
Opened 2024-07-31 15:56 UTC by yyorkchan

2024-08-01 13:38 UTC, cychiuae commented on pkg/util/validation/formats.go
> +	_, err = ldap.CompileFilter(result)
The message is not readable and it expose too much implementation detail

2024-08-01 13:50 UTC, cychiuae commented on pkg/lib/config/testdata/parse_secret_tests.yaml
> +      data: {}
Try to be specific in the commit message.

> Update secret test yaml 

What are you updating? Everyone knows you are updating secret test yaml but for what.

2024-08-01 13:51 UTC, cychiuae commented on pkg/lib/config/config.go
> +	LDAP *LDAPConfig `json:"ldap,omitempty"`
I dont think this is a fix.

2024-08-01 13:55 UTC, cychiuae commented on pkg/lib/config/secret.go
> +			for _, user := range ldapServerUserCredentials.Items {
It is not a `user`. Please rename it.

2024-08-02 07:05 UTC, cychiuae commented on pkg/lib/config/secret_ldap.go
> +		"name": { "type": "string" },
Do we need to add `minLength: 1` checking to name?

2024-08-02 07:05 UTC, cychiuae commented on pkg/lib/config/testdata/parse_secret_tests.yaml
> +            dn: dc=test
End this file will a newline

2024-08-02 07:05 UTC, cychiuae commented on pkg/lib/config/testdata/secret_config_validate_tests.yaml
> +          password: "password"
End this file will a newline

2024-08-05 04:46 UTC, louischan-oursky requested changes

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/ldap.go
> +			"minItems": 1
Remove this. If you reference OAuth providers, there is no `minItems` there.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/ldap.go
> +var _ = SecretConfigSchema.Add("LDAPServerUserCredentials", `
Move secret related things in `secret_ldap.go`. Take `bot_protection.go` and `secret_bot_protection.go` as references.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/ldap.go
> +		"password": { "type": "string" }
`dn` and `password` should have `minLength: 1`

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/ldap.go
> +		"items": { "type": "array", "items": { "$ref": "#/$defs/LDAPServerUserCredentialsItem" } }
Add programmatic validation to ensure if a server is defined, then it has a corresponding item in the secrets. You can also reference bot protection on how to do this.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/util/validation/formats.go
> +			break
The search filter template MUST pass all three test cases in order to be considered as valid. So the loop should look like

```golang
testcases := []string{"+85298765432", "username", "test@test.com"}
for _, testcase := range testcases {
  var buf bytes.Buffer // Note that buf is moved into the loop. You do not need it outside the loop.
  err := tmpl.Execute(&buf, map[string]string{"Username": testcase})
  if err != nil {
    return err
  }
  filterString := buf.String()
  _, err := ldap.CompileFilter(filterString)
  if err != nil {
    return err
  }
}

// If no early return, then the filter template is considered as valid.
return nil
```

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/util/validation/formats.go
> +	// numericoid = number 1*( DOT number )
Include the relevant production rules as comment here.

```go
// numericoid = number 1*( DOT number )
// number  = DIGIT / ( LDIGIT 1*DIGIT )
// DIGIT   = %x30 / LDIGIT       ; "0"-"9"
// LDIGIT  = %x31-39             ; "1"-"9"
// https://datatracker.ietf.org/doc/html/rfc4512#section-1.4
```

Then you will see what you implement here is not strictly correct. You did not handle number with leading zeros.

Please add test cases for leading zeros.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/testdata/parse_secret_tests.yaml
> +        username: user
I think the field is called `dn` not `username`, how come it is valid?

Also, please add more test cases, like minLength, dependentRequired. The baseline is, you test every schema you write.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/util/validation/formats.go
> +	tmpl, err := template.New("search_filter").Parse(strings.Trim(str, "\n"))
I think you do not need to trim space here, you just need to trim space on the rendered result.

2024-08-05 04:46 UTC, louischan-oursky commented on pkg/lib/config/secret.go
> +
Add test cases for this.

2024-08-05 10:54 UTC, louischan-oursky requested changes

2024-08-05 10:54 UTC, louischan-oursky commented on pkg/util/validation/formats.go
> +	matched, err := regexp.MatchString(`^[1-9](\.\d+)*$`, str)
This is still incorrect. For example, `1.01` is valid against this regex, but invalid as an oid.

2024-08-05 10:54 UTC, louischan-oursky commented on pkg/util/validation/formats_test.go
> +		So(f("0.1.3"), ShouldBeError, "invalid OID")
`0.1.3` is actually a valid oid. This testcase is incorrect.

2024-08-05 10:54 UTC, louischan-oursky commented on pkg/lib/config/testdata/secret_config_validate_tests.yaml
> +          user_id_attribute_oid: "1.9.2342.19200300.100.1.1"
Revert this change

2024-08-05 10:54 UTC, louischan-oursky commented on pkg/lib/config/testdata/secret_config_validate_tests.yaml
> +          user_id_attribute_oid: "1.9.2342.19200300.100.1.1"
Revert this line

2024-08-05 10:54 UTC, louischan-oursky commented on pkg/lib/config/testdata/secret_config_validate_tests.yaml
> +          user_id_attribute_oid: "1.9.2342.19200300.100.1.1"
Revert this line

2024-08-05 11:46 UTC, yyorkchan commented
Thanks @louischan-oursky

2024-08-06 03:57 UTC, louischan-oursky requested changes

2024-08-06 03:57 UTC, louischan-oursky commented on pkg/lib/config/testdata/parse_secret_tests.yaml
> +  /secrets/0/data/items/0: dependentRequired
When we use dependentRequired, the error shape changed a bit. This is unexpected. Let's use allOf and if then to implement the condition.


```
{
  "allOf": [
    {
      "if": {
         "required": ["dn"]
       },
       "then": {
          "required": ["password"]
       },
    },
    {
      "if": {
         "required": ["password"]
       },
       "then": {
          "required": ["dn"]
       },
    },
  ]
}

```

2024-08-06 03:57 UTC, louischan-oursky commented on pkg/lib/config/testdata/parse_secret_tests.yaml
> +    map[Required:map[password:map[actual:[name password] expected:[dn] missing:[dn]]]]
Note that the map has `Required`, which is not compatible with other error.

2024-08-06 03:57 UTC, louischan-oursky commented on pkg/util/validation/formats_test.go
> +		So(f("1.1.1.a.2"), ShouldBeError, "invalid OID")
Add a test case to show your regex can handle `0.01`

2024-08-06 10:22 UTC, louischan-oursky requested changes

2024-08-06 10:22 UTC, louischan-oursky commented on pkg/lib/config/ldap.go
> +		"user_id_attribute_name": { "type": "string", "format": "ldap_attribute" }
The format is called `ldap_attribute_name`

2024-08-06 10:22 UTC, louischan-oursky commented on pkg/util/validation/formats.go
> +	matched, err := regexp.MatchString(`^[a-zA-Z\d-]+$`, str)
But attribute name starting with a hyphen is uncommon. Let's use production rule of `keystring` here. Update the comment to reflect this implementation choice.

2024-08-06 10:22 UTC, louischan-oursky commented on pkg/util/validation/formats_test.go
> +		So(f("dc=example,dc=com"), ShouldBeError, "invalid attribute")
Add a test to show we forbid attribute name starting with a digit or a hyphen.

2024-08-06 12:15 UTC, louischan-oursky approved these changes

2024-08-06 12:23 UTC, merged