Fix import api failed to handle email username with upper cases
authgear/authgear-server pull request #4557
Opened 2024-08-08 20:04 UTC by pkong-ds

Pending test case

2024-08-09 12:10 UTC, pkong-ds commented
@louischan-oursky updated, thanks!

2024-08-12 10:11 UTC, louischan-oursky requested changes
1. Rename StandardAttributesList() to NonIdentityAwareStandardAttributesList()
2. Fix the failing test.

2024-08-12 10:19 UTC, pkong-ds commented
@louischan-oursky local CI pass now, thanks!

2024-08-12 11:01 UTC, louischan-oursky approved these changes

2024-08-12 11:04 UTC, merged