Add test cases for admin api create user & change password
authgear/authgear-server pull request #4588
Opened 2024-08-14 02:35 UTC by IniZio

ref DEV-1646

2024-08-14 06:51 UTC, louischan-oursky requested changes

2024-08-14 06:51 UTC, louischan-oursky commented on e2e/var/authgear.yaml
> -  email:
I think you now need to suppress SMS, because you turn off DEV mode.

2024-08-14 06:51 UTC, louischan-oursky commented on go.mod
> +
These dependencies are used in e2e only. I think we should make `./e2e` a separate go module, like `./custombuild`.

Then this PR should make no changes to `<project_root>/go.mod`

2024-08-14 06:51 UTC, louischan-oursky commented on e2e/pkg/testrunner/testcase.go
> +	cmd.AppID = appID
Why?

It looks to me that this should look like

```
cmd, err := NewEnd2EndCmd(NewEnd2EndCmdOptions{
  TestCase: *tc,
   Test: t,
})
if err != nil {
  t.Errorf("failed to create e2e cmd: %v", err)
  return
}

// And then you can use cmd.AppID
```

2024-08-14 06:51 UTC, louischan-oursky commented on e2e/tests/admin_api/create_user_test.go
> +	)
Too much details to set up a test case. I expect

```
cmd, err := NewEnd2EndCmd(...)

cmd.Client.GraphQLAPI(...)
cmd.CheckEmail(...)

rows, err := cmd.QuerySQLSelectRaw(...) // rows is of type []map[string]interface{}
```

2024-08-14 06:51 UTC, louischan-oursky commented on e2e/pkg/e2eclient/client.go
> +		Message string `json:"message"`
You test against the public API. Message is not part of the public API. You assert `reason`.

2024-08-14 09:13 UTC, pkong-ds commented on e2e/Makefile
> +
👍 🥇 🙇

2024-08-14 13:00 UTC, louischan-oursky commented
@IniZio Build failed.

2024-08-15 04:26 UTC, louischan-oursky approved these changes

2024-08-15 04:27 UTC, merged