Check if ldap identity is compatible with account linking
authgear/authgear-server pull request #4607
Opened 2024-08-15 11:09 UTC by yyorkchan

Incoming LDAP on existing email
https://github.com/user-attachments/assets/81ee1f88-0181-40db-826d-f7c417bdd99a

Incoming LoginID on existing LDAP
https://github.com/user-attachments/assets/05571bc3-f6c9-45de-8be1-c763b0c89759

2024-08-16 11:35 UTC, louischan-oursky commented
@yyorkchan I have merged the dependency. Please rebase.

2024-08-19 03:03 UTC, yyorkchan commented
Rebased Thanks @louischan-oursky

2024-08-19 07:10 UTC, yyorkchan commented
Updated Thanks @louischan-oursky

2024-08-19 07:27 UTC, louischan-oursky requested changes

2024-08-19 07:27 UTC, louischan-oursky commented on e2e/tests/account_linking/incoming_oauth_conflicts_ldap.test.yaml
> +    user_import: ldap_user.json
This import is useless. Your test relies on `ldap_user.sql` to work.

2024-08-19 07:27 UTC, louischan-oursky commented on e2e/tests/account_linking/ldap_user.sql
> +    '{"dn": "cn=mock,ou=people,ou=HK,dc=authgear,dc=com", "uid": "mock", "mail": "mock@example.com"}'
This is incorrect.

1. Attributes are array, not just a string
2. Attributes are stored in bytes encoded in base64.

2024-08-19 08:48 UTC, louischan-oursky approved these changes

2024-08-19 08:53 UTC, merged