Add User Details Disable/Delete tab
authgear/authgear-server pull request #4613
Opened 2024-08-16 07:40 UTC by toml5566

ref DEV-1752

<img width="1505" alt="Screenshot 2024-08-16 at 3 39 03 PM" src="https://github.com/user-attachments/assets/6be379eb-190e-43dd-9d31-fb9750518b92">
<img width="1505" alt="Screenshot 2024-08-16 at 3 39 10 PM" src="https://github.com/user-attachments/assets/a7b9b014-06eb-4631-869a-84d3b87fb952">
<img width="1505" alt="Screenshot 2024-08-16 at 3 39 22 PM" src="https://github.com/user-attachments/assets/91fafa30-bf03-456b-a6d0-74299afcd268">
<img width="1505" alt="Screenshot 2024-08-16 at 3 39 32 PM"
<img width="1505" alt="Screenshot 2024-08-16 at 3 39 39 PM" src="https://github.com/user-attachments/assets/113e2935-b12b-4592-a92a-2abade13225e">
 src="https://github.com/user-attachments/assets/4507644c-1b32-4796-826d-7d1aef2374bf">

2024-08-19 09:06 UTC, louischan-oursky requested changes

2024-08-19 09:06 UTC, louischan-oursky commented on portal/src/graphql/adminapi/UserDetailsAdminActions.tsx
> +            className={cn(styles.actionCellActionButton, styles.actionBorder)}
actionCellActionButton modifies padding, which is considered as the implementation details of DefaultButton. You use `styles` to override padding. In general, you use `className` to position the component, and use specific prop, like `variant`, `styles` to customize the Fluent component.

2024-08-19 09:06 UTC, louischan-oursky commented on portal/src/graphql/adminapi/UserDetailsScreen.tsx
> +          }}
You define constants with `const` in this file.

2024-08-19 09:21 UTC, louischan-oursky requested changes

2024-08-19 09:21 UTC, louischan-oursky commented on portal/src/graphql/adminapi/UserDetailsAdminActions.tsx
> +          <DefaultButton
Introduce a new component AdminActionButton. Handle merging the styles from prop, and the inherit styles of the design of this component. useMergedStylesPlain

2024-08-21 09:18 UTC, toml5566 commented
@louischan-oursky Updated, please feel free to review

2024-08-22 03:20 UTC, louischan-oursky approved these changes

2024-08-22 03:21 UTC, merged