Missing loading state when the preview is pending re render
authgear/authgear-server pull request #4614
Opened 2024-08-16 07:49 UTC by yyorkchan

Demo:
https://github.com/user-attachments/assets/7a49e645-3f9a-4b7b-a71e-8bbe033c6b3f

- Now Design Screen theme customisation changes synchronously 
- Select Preview Page shows loading

2024-08-16 10:10 UTC, cychiuae requested changes

2024-08-16 10:10 UTC, cychiuae commented on authui/src/inline-preview.ts
> +    theme: message.theme ?? {},
The fallback value should have the same type as the `message.theme`

2024-08-16 10:10 UTC, cychiuae commented on authui/src/inline-preview.ts
> +    }
Here you will also remove other classes. Please just add/more remove the class we are targeting.

2024-08-16 10:10 UTC, cychiuae commented on portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
> +  const [isIframeLoading, setisIframeLoading] = useState(true);
`setisIframeLoading` -> `setIsIframeLoading`

2024-08-16 10:10 UTC, cychiuae commented on portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
> +      {isIframeLoading ? <ShowLoading /> : null}
Please pay more attention to the ui you introduce

<img width="1645" alt="Screenshot 2024-08-16 at 6 06 10 PM" src="https://github.com/user-attachments/assets/7a53b2f3-bd44-4eab-bd46-65f8d3b2402b">

2024-08-16 11:45 UTC, louischan-oursky requested changes

2024-08-16 11:45 UTC, louischan-oursky commented on authui/src/inline-preview.ts
> +    el.setAttribute("class", customisationMessage.theme);
If you look at authui/src/colorscheme.ts, you will see there is no `light` or `auto`. You have to study how light/dark works in Auth UI first. You never guess.

2024-08-16 12:01 UTC, louischan-oursky approved these changes

2024-08-16 13:04 UTC, cychiuae commented on portal/src/graphql/portal/DesignScreen/DesignScreen.tsx
> +
I suggest just add an effect to set loading to true whenever src is changed

2024-08-19 03:21 UTC, louischan-oursky approved these changes

2024-08-19 03:22 UTC, merged