Implement missing milestones on inspect device token
authgear/authgear-server pull request #4628
Opened 2024-08-20 10:08 UTC by pkong-ds

## Preview
Pending

2024-08-20 10:09 UTC, louischan-oursky commented
Maybe we can add e2e tests for this.

2024-08-21 09:10 UTC, pkong-ds commented
@louischan-oursky The cookie jar somehow not working. Problems I encountered

1. cookie set in jar, but request unable to get cookie, even if same URL
2. Unable to use `http.Client` cookies feature like `auto-add cookie to request` and `auto-set cookie on receive Response with "Set-Coookie" header`

2024-08-21 11:17 UTC, pkong-ds commented
@louischan-oursky thanks a lot for the instruction on `implementing my own Jar`

Found out the problem was `127.0.0.1` host did not match domain `portal.locahost`, which threw `cookiejar: illegal cookie domain attribute` error. 

I fixed it by
- forking official cookie jar to e2e test pkgs
- https://github.com/authgear/authgear-server/pull/4628/commits/6dd3cf1eb99d4a13d2ce562148f0b230832e4754

🙏

2024-08-22 05:38 UTC, louischan-oursky requested changes

2024-08-22 06:58 UTC, louischan-oursky approved these changes

2024-08-22 06:58 UTC, merged