Implement authui v2 navbar
authgear/authgear-server pull request #4662
Opened 2024-08-27 03:27 UTC by cychiuae

based on #4640

2024-08-27 03:28 UTC, cychiuae commented
@yyorkchan @Kuixz Please take a look at the last commit i made

2024-08-29 03:05 UTC, louischan-oursky approved these changes

2024-08-29 03:09 UTC, louischan-oursky requested changes

2024-08-29 03:09 UTC, louischan-oursky commented on resources/authgear/templates/en/web/authflowv2/__navbar.html
> +    <span class="inline-block ml-3">{{ .BackTitle }}</span>
We need to use `ltr:ml-3 rtl:mr-3`. Or you use gap

@yyorkchan @cychiuae We need to pay attention to the left/right usage. If you use explicit left/right class, then you probably need to write `ltr:` and `rtl:`

2024-08-29 04:16 UTC, louischan-oursky approved these changes

2024-08-29 04:19 UTC, merged