Fix bot protection input channel not inherited from previous screen
authgear/authgear-server pull request #4686
Opened 2024-09-03 05:58 UTC by pkong-ds

ref DEV-1904

The problem was `channel` defaulted as `options[0].Channel` in `takeBranchLoginAuthenticate`, but this default channel is not inherited in the captcha redirect screen

2024-09-03 07:30 UTC, louischan-oursky requested changes
I added a commit to fix the alias problem. Please help me to test any regression manually.

2024-09-03 07:41 UTC, pkong-ds commented
## Preview 1 - bot protection bug gone

https://github.com/user-attachments/assets/07de464c-650e-4c4e-ae30-a5bf7772cfe7

## Preview 2 - signup ok

https://github.com/user-attachments/assets/ea04bf31-9910-4831-bc99-54742a247826

## Preview 3 - login + 2fa oob otp ok

See preview 1

## Preview 4 - reauth + 2fa oob otp ok
Pending

2024-09-03 07:46 UTC, pkong-ds commented
@louischan-oursky see above comment, seems no regression

2024-09-04 03:35 UTC, louischan-oursky approved these changes

2024-09-04 03:39 UTC, merged