Stricten user import schema
authgear/authgear-server pull request #4687
Opened 2024-09-03 06:28 UTC by pkong-ds

ref DEV-1482

Some directions I thought of, but only implemented the checked ones
- [x] add `minLength: 1` to required string fields
- [ ] add regex to some expected fields, like email, phone number, birthdate
- [ ] add enum to expected fields, like zoneinfo, locale

ref https://docs.authgear.com/how-to-guide/user-management/import-users-using-user-import-api#input-format

@louischan-oursky see if you expected more strict rules? thanks 🙏

2024-09-04 03:51 UTC, louischan-oursky requested changes
In pkg/lib/authn/stdattrs/validate.go, there are the actual schema that the std attr module will use to validate the standard attributes. We can borrow the schemas there.

We must pay attention to one thing. validation.SchemaBuilder is just a map, so we must not mutate the schema in stdattrs. I am saying this because the schema used in userimport is slightly different from the schemas in stdattrs. In particular, the schema in userimport allows null.

So my suggestion is

1. Make the SchemaBuilder* in stdattrs private. To avoid external modules import them and mutate them accidentally.
2. Expose methods to make new SchemaBuilder in stdattrs. So that the logic still live in stdattrs.
3. Call the newly exposed methods in userimport to validate more strict.

2024-09-04 07:49 UTC, pkong-ds commented
@louischan-oursky updated, thanks!

2024-09-04 11:28 UTC, louischan-oursky requested changes

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +func (b SchemaBuilder) Copy() SchemaBuilder {
Clone()

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +			newB[k] = vb.Copy()
Clone()

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +	existingTypes := b["type"]
value, ok := b["type"]

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +	if existingTypes == nil {
if !ok

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +func (b SchemaBuilder) Nullable() SchemaBuilder {
AddTypeNull()

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +func (b SchemaBuilder) Nullable() SchemaBuilder {
Move near to `Type()` and `Types()`

2024-09-04 11:28 UTC, louischan-oursky commented on pkg/util/validation/schema_builder.go
> +		b.Type(TypeNull)
This new method should look like `AddRequired()`

2024-09-04 11:39 UTC, pkong-ds commented
Updated, thanks!

2024-09-04 13:15 UTC, louischan-oursky requested changes

2024-09-04 13:15 UTC, louischan-oursky commented on pkg/lib/userimport/model.go
> +func mapGetAddTypeNull[M ~map[string]interface{}, T constraints.Ordered | ~bool](m M, key string) (*T, bool) {
Revert this change.

2024-09-04 13:17 UTC, pkong-ds commented
@louischan-oursky sor, fixed up~

2024-09-05 03:53 UTC, louischan-oursky approved these changes

2024-09-05 03:53 UTC, merged