Support Hot Module Replacement using Vite
authgear/authgear-server pull request #4706
Opened 2024-09-05 10:14 UTC by andychow326

ref DEV-2008

2024-09-05 10:34 UTC, louischan-oursky requested changes

2024-09-05 10:34 UTC, louischan-oursky commented on authui/package.json
> +    "dev": "vite",
`make authui-dev`

2024-09-05 10:34 UTC, louischan-oursky commented on authui/packages/vite-plugin-authgear-authui/src/index.js
> +      // Rewrite node attributes by condition
if this is `script src`
if this is `link rel=stylesheet href`

2024-09-06 04:00 UTC, louischan-oursky requested changes
![SCR-20240906-kvcq](https://github.com/user-attachments/assets/ca2e6df0-e54e-43ff-bc36-420c3cbcadef)
![SCR-20240906-kviz](https://github.com/user-attachments/assets/817edc4a-fb56-4ebb-89a0-a5a342323a06)

Looks like you did not handle other kind of asset properly.

2024-09-06 05:12 UTC, andychow326 commented
> ![SCR-20240906-kvcq](https://private-user-images.githubusercontent.com/15082564/365028942-ca2e6df0-e54e-43ff-bc36-420c3cbcadef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTkyNDQsIm5iZiI6MTcyNTU5ODk0NCwicGF0aCI6Ii8xNTA4MjU2NC8zNjUwMjg5NDItY2EyZTZkZjAtZTU0ZS00M2ZmLWJjMzYtNDIwYzNjYmNhZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTg2Njc2NmIzZmJlOGNhNTQ2NzI2YmM0MDlkMGYzMzE2NTdmYmQwN2VhNDJhM2QxYTBjZWE0ODMxMmZiN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8qKlA42Xjey2Y1KEis80408XP1oZJVvNg5f4-J3--0Q) ![SCR-20240906-kviz](https://private-user-images.githubusercontent.com/15082564/365028952-817edc4a-fb56-4ebb-89a0-a5a342323a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTkyNDQsIm5iZiI6MTcyNTU5ODk0NCwicGF0aCI6Ii8xNTA4MjU2NC8zNjUwMjg5NTItODE3ZWRjNGEtZmI1Ni00ZWJiLTg5YTAtYTVhMzQyMzIzYTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NzVhMDMzYTYxOGE0MjViNTlmNjQwODg4ZWU5MDM3YWM4MTM3M2I3ZThjYjY5MjI2MWZmM2IyZjM2NGI1NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._04ChdR2kxwFMbnMy7jt4-W8tuPm4Eb8UsjyKcqnxnc)
> 
> Looks like you did not handle other kind of asset properly.

@louischan-oursky It looks like there are 2 problems to be fixed:
- Seems it is required to run `make authui` before `make authui-dev` as there are some other places using `call $.GeneratedStaticAssetURL` other than `__generated_asset.html`. (Fixed by [c28b3dc](https://github.com/authgear/authgear-server/pull/4706/commits/c28b3dc8767ad628971879c9b225d263050b2821))
- Noticed that `Twemoji.Mozilla-subset.woff2` still cannot be imported even the above is fixed. It is because the hash removing process for `Twemoji.Mozilla-subset.woff2` is not correctly handled. (Fixed by [94d8b45](https://github.com/authgear/authgear-server/pull/4706/commits/94d8b45f9ab11c6d87f82498997364729a80d5f7))

2024-09-06 06:04 UTC, louischan-oursky approved these changes

2024-09-06 06:05 UTC, merged