Also check `printf` and `Translations.HasKey` in translation key linter
authgear/authgear-server pull request #4725
Opened 2024-09-10 13:39 UTC by pkong-ds

ref DEV-1944

2024-09-11 08:35 UTC, pkong-ds commented
Ready for review, thanks

2024-09-11 10:53 UTC, louischan-oursky requested changes

2024-09-11 10:53 UTC, louischan-oursky commented on devtools/gotemplatelinter/translation_key_rule_special_cases.go
> +}
Remove printfFalsePositives.

2024-09-11 11:26 UTC, pkong-ds commented
Updated, thanks!

2024-09-11 14:02 UTC, pkong-ds commented
Thanks, did you change something? 🙏

2024-09-12 02:33 UTC, louischan-oursky commented
I rebased and run `make lint-translation-keys` to resolve the conflicts for you.

2024-09-12 02:33 UTC, louischan-oursky approved these changes

2024-09-12 02:44 UTC, merged