Consolidate template variables for OTP and forgot password
authgear/authgear-server pull request #4728
Opened 2024-09-11 08:55 UTC by chankiyu22

refs DEV-2023

2024-09-11 10:24 UTC, louischan-oursky requested changes
1. You do not change the dependencies of the caller.
2. The caller uses a new strong type.
3. In pkg/lib/translation/service.go, no more map[string]interface{}
4. Preserve the original behavior.
5. InputTemplateVariables -> PreparedTemplateVariables
6. In your interface, you take InputTemplateVariables
7. In pkg/lib/translation/service.go, you make InputTemplateVariables into PreparedTemplateVariables

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/translation/template.go
> +type EscapedString string
Remove this.

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	GetAppName() (appName string, err error)
Remove this. The caller should not be asked to do more things.

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	StaticAssets    translation.StaticAssetResolver
Remove this.

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	uiParam := uiparam.GetUIParam(s.Context)
Remove this.

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	return translation.MakeOTPTemplateVariables(
You do not call this function here.

2024-09-11 10:24 UTC, louischan-oursky commented on pkg/lib/feature/forgotpassword/service.go
> +		HasPassword: len(ais) > 0,
PartialTemplateVariables

2024-09-11 10:25 UTC, louischan-oursky requested changes

2024-09-11 10:25 UTC, louischan-oursky commented on pkg/lib/translation/template.go
> +package translation
variables.go

2024-09-12 03:33 UTC, chankiyu22 commented
@louischan-oursky Updated.

2024-09-12 06:19 UTC, louischan-oursky requested changes

2024-09-12 06:19 UTC, louischan-oursky commented on pkg/lib/translation/service.go
> +	err = s.appMetadata(variables)
This changes the original behavior.

The original behavior is 

```
data := {}
err := s.appMetadata(data)
// data = {"AppName": "blahblahblah" }

Then data is used to render sender, replyTo, and subject
```

2024-09-12 06:19 UTC, louischan-oursky commented on pkg/lib/translation/service.go
> +	err = s.appMetadata(variables)
Same here.

2024-09-12 06:23 UTC, louischan-oursky requested changes

2024-09-12 06:23 UTC, louischan-oursky commented on pkg/lib/translation/service.go
> +	}, s.StaticAssets.StaticAssetURL)
Please add new tests for EmailMessageData, SMSMessageData, and WhatsappMessageData to show the public API does not change.

2024-09-12 07:48 UTC, chankiyu22 commented on pkg/lib/translation/variables.go
> +	AppName  string
Remove this as the body should have no use.

2024-09-12 07:48 UTC, chankiyu22 commented on pkg/lib/translation/variables.go
> +) *PreparedTemplateVariables {
Move it under translation service
- Also prepare AppName

```golang
func (s *Service) PrepareTemplateVariables(variables *PartialTemplateVariables) {
    appName, err := ...
    return &PreparedTemplateVariables{
        AppName: appName,
        ...,
        StaticAssetURL: s.StaticAssets.StaticAssetURL,
    }, err
}
```

2024-09-13 02:38 UTC, chankiyu22 reviewed
@louischan-oursky Can take a look now. Note that there are some behaviour change :adore2x:

2024-09-13 07:26 UTC, louischan-oursky approved these changes

2024-09-13 07:41 UTC, merged