[Deps #4745] [DEV-2022] Add more fields when send SMS
authgear/authgear-server pull request #4748
Opened 2024-09-16 07:16 UTC by chankiyu22

refs DEV-2022

```
WARN[0031] skip sending SMS in development mode          app=my-app app_id=my-app body="Setup two-step verification on Authgear with this one-time password 353888.\n\nDon't share it with anyone.\n" language_tag=en logger=sms-client recipient=+85298765432 sender=Authgear template_name=messages/setup_secondary_oob_sms.txt template_variables="&{Authgear  353888  false accounts.portal.localhost:3100   +85298765432    }"
```

2024-09-16 13:21 UTC, louischan-oursky commented
Please rebase.

2024-09-17 02:47 UTC, chankiyu22 commented
@louischan-oursky rebased.

2024-09-17 03:41 UTC, louischan-oursky requested changes
I found another change we need to address.

1. Currently there is `Name` in MessageSpec. The usage of `Name` is to construct a translation key. So please rename `Name` to `KeyComponentInTranslationJSON`.
2. Now that we know `KeyComponentInTranslationJSON` is not a general name. So you do not include it as extra fields.
3. There is a weird type nonblocking.MessageType. Temporarily delete it.
4. By deleting nonblocking.MessageType, you will encounter compilation errors. So our next step is to fix them. We want our code no longer depend on nonblocking.MessageType
5. nonblocking.MessageType ultimately will be written in the audit log. In addition to nonblocking.MessageType, we want to record the actual template name. The actual template name is `something.html` or `something.txt`.

2024-09-17 03:41 UTC, louischan-oursky commented on pkg/lib/infra/sms/variables.go
> +	AppName     string `json:"app_name"`
Add omitempty to all fields.

2024-09-17 04:23 UTC, louischan-oursky requested changes

2024-09-17 04:23 UTC, louischan-oursky commented on pkg/lib/infra/sms/custom.go
> +	TemplateName      string             `json:"template_name"`
MessageType string `json:"message_type"`
TemplateName string `json:"template_name"` (basename of the logic path)

2024-09-17 04:23 UTC, louischan-oursky commented on pkg/lib/infra/sms/custom.go
> +	LanguageTag       string             `json:"preferred_language_tags"`
language_tag

2024-09-17 07:10 UTC, chankiyu22 commented
@louischan-oursky Updated.

2024-09-17 09:25 UTC, louischan-oursky requested changes
1. nonblocking.MessageType -> translation.MessageType
2. MessageSpec.Name (string -> SpecName)
3. Add new field MessageSpec.MessageType -> MessageType
4. There is a function `(Form, otp.MessageType) -> (MessageSpec, nonblock.MessageType)`. After the change (Form, translation.MessageType) -> MessageSpec
5. Outsiders use MessageType only, they do not use SpecName.
6.

2024-09-17 09:25 UTC, louischan-oursky commented on pkg/lib/translation/message_type.go
> +package translation
This file should have name `message_declarations.go`

2024-09-17 09:32 UTC, louischan-oursky requested changes

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	PrepareSMS(phoneNumber string, msgType string) (*messaging.SMSMessage, error)
Change the type to translation.MessageType

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/authn/otp/sender.go
> +	PrepareWhatsapp(phoneNumber string, msgType string) (*messaging.WhatsappMessage, error)
Change the type to translation.MessageType

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/messaging/message_email.go
> +	Type string
translation.MessageType

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/messaging/message_sms.go
> +	Type string
translation.MessageType

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/messaging/message_whatsapp.go
> +	Type         string
translation.MessageType

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/message.go
> +	Type              MessageType
Name SpecName

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/message_type.go
> +	MessageTypeVerification                   MessageType = "verification"
SpecNames

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/message_type.go
> +		Type:              MessageTypeVerification,
Ensure they have SpecName and Type.

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/service.go
> +func (s *Service) emailMessageHeader(name MessageType, variables *PreparedTemplateVariables) (sender, replyTo, subject string, err error) {
name SpecName

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/service.go
> +func (s *Service) smsMessageHeader(name MessageType, variables *PreparedTemplateVariables) (sender string, err error) {
name SpecName

2024-09-17 09:32 UTC, louischan-oursky commented on pkg/lib/translation/service_test.go
> +			Type:              "test",
Update accordingly.

2024-09-19 07:06 UTC, chankiyu22 commented
@louischan-oursky updated.

2024-09-19 08:30 UTC, louischan-oursky requested changes

2024-09-19 08:30 UTC, louischan-oursky commented on pkg/lib/infra/sms/client.go
> +	) error
Take SendOptions directly.

2024-09-19 10:10 UTC, chankiyu22 commented
@louischan-oursky updated.

2024-09-19 11:56 UTC, louischan-oursky approved these changes

2024-09-19 11:56 UTC, merged