[WIP] SAML/SLO: Return a response in logout endpoint
authgear/authgear-server pull request #4749
Opened 2024-09-16 07:30 UTC by tung2744

ref DEV-2060

TODO:
- [ ] Put the signature of the response to query if using redirect binding

2024-09-17 05:04 UTC, louischan-oursky requested changes
1. Delete samlerror. Move the contents to samlprotocol/error_blahblahblah.go
2. Delete samlprotocolhttp. Move the contents to samlbinding.
3. Remove IsInternalError()

2024-09-17 05:04 UTC, louischan-oursky commented on pkg/auth/handler/saml/logout.go
> +	var err error
1. Prefer more than one methods returning (A, error). The error could be a error result that can be written directly.
2. One method to see the flow e.g. handleSLORequest

```
func handleSLORequest() {
  request, err := parse(r)
}
```


```
var err error

defer func() {
  if err != nil {
    // ...
  }
}()



switch {
case A
  if err != nil {
    return
  }
case B
}
```

2024-09-17 10:45 UTC, tung2744 commented
Updated, thanks!

2024-09-19 04:14 UTC, louischan-oursky requested changes

2024-09-19 04:14 UTC, louischan-oursky commented on pkg/auth/handler/saml/logout.go
>  			break
No break

2024-09-19 04:14 UTC, louischan-oursky commented on pkg/auth/handler/saml/logout.go
> +			break
No break

2024-09-19 04:14 UTC, louischan-oursky commented on pkg/auth/handler/saml/logout.go
> +			break
No break

2024-09-19 04:14 UTC, louischan-oursky commented on pkg/auth/handler/saml/logout.go
> +			break
No break

2024-09-19 08:17 UTC, louischan-oursky approved these changes

2024-09-19 08:20 UTC, merged

2024-09-20 07:41 UTC, tung2744 commented
I found that I forgot to remove the samlerror package, although no code is using them. I will remove them in next pr.