Specify browserslistrc more accurately
authgear/authgear-server pull request #4766
Opened 2024-09-24 08:06 UTC by pkong-ds

[New authUI coverage: 85.6%](https://browsersl.ist/#q=iOS+%3E%3D+14%0Alast+5+Chrome+versions%0Alast+5+ChromeAndroid+versions%0Alast+5+Edge+versions%0Alast+5+Safari+versions+%23+non-iOS+Safari%0Alast+5+Firefox+versions%0Alast+5+FirefoxAndroid+versions%0Alast+2+Samsung+versions+%23+Samsung+default+browser+-+Samsung+Internet%0Anot+dead+%23+no+browsers+without+security+updates%0A)

Fixed

- `Android` referred to Android webview instead of all browsers on Android
- included more versions, some browsers like Chrome 127 is still the most popular (current 129, that makes Chrome 127 not included in `last 2 Chrome versions`

2024-09-24 08:18 UTC, louischan-oursky requested changes

2024-09-24 08:18 UTC, louischan-oursky commented on authui/.browserslistrc
> +not dead # no browsers without security updates
What about

```
iOS >= 14
Safari >= 14
Android >= 5.0
last 5 Chrome versions
last 5 ChromeAndroid versions
last 5 Edge versions
last 5 Firefox versions
last 5 FirefoxAndroid versions
last 2 Samsung versions
not dead
```

2024-09-24 12:08 UTC, pkong-ds commented
Updated, thanks!

2024-09-25 02:51 UTC, louischan-oursky requested changes

2024-09-25 02:51 UTC, louischan-oursky commented on .github/workflows/ci.yaml
> +      working-directory: ./authui
/portal

2024-09-25 03:00 UTC, pkong-ds commented
Sor; updated, thanks!

2024-09-25 04:17 UTC, louischan-oursky approved these changes

2024-09-25 04:19 UTC, merged