Update brand logo margin
authgear/authgear-server pull request #4767
Opened 2024-09-25 03:51 UTC by pkong-ds

ref DEV-2016

portal height slider in next PR.

## Preview

Pending

2024-09-25 11:30 UTC, louischan-oursky requested changes

2024-09-25 11:30 UTC, louischan-oursky commented on resources/authgear/templates/en/web/authflowv2/__brand_logo.html
> +  <div class="brand-logo__container light" data-src="{{ $light }}">
Copy data-previewable-*

2024-09-25 11:30 UTC, louischan-oursky commented on authui/src/authflowv2/components/settings-header.css
> +    @apply hidden; /* NOTE(DEV-2123): Hide setting header for now */
Remove this commit.

2024-09-25 13:51 UTC, pkong-ds commented
Updated thanks!

2024-09-26 03:17 UTC, pkong-ds commented
Thanks 🙏

2024-09-26 03:40 UTC, louischan-oursky commented
@pkong-ds I added 3 commits.

2024-09-26 03:54 UTC, pkong-ds commented
@louischan-oursky I did not use gap in screen-logo-layout because it's not the only place that uses brand logo.

I believe __direct_access and __settings_header both use it. If the margin is removed without adding gap to these 2 files, the existing UI will probably break.

Maybe we should add gap to those 2, or keep margin bottom?

2024-09-26 03:54 UTC, pkong-ds commented
Also, curious, is object contain really necessary with flex?

2024-09-26 05:27 UTC, louischan-oursky approved these changes

2024-09-26 05:29 UTC, pkong-ds commented
Per offline discussion

> __direct_access and __settings_header both use it

__direct_access - Fixed by @louischan-oursky in [cf53deb](https://github.com/authgear/authgear-server/pull/4767/commits/cf53debc8ad9a493f3abbf19ac4b8eb99b3a3123), [42ef98b](https://github.com/authgear/authgear-server/pull/4767/commits/42ef98b1a2954531ad15f083bfb30f842ea1af7f)
__settings_header - to be removed in PR #4770 

> is object contain really necessary

Turns out it was a bug previously, @louischan-oursky helped fix it in [b5224dc](https://github.com/authgear/authgear-server/pull/4767/commits/b5224dc9e65abd5b4cc7f607bf1285969324fa2e)

2024-09-26 05:53 UTC, merged