Update page not found title copywriting
authgear/authgear-server pull request #4769
Opened 2024-09-25 08:20 UTC by pkong-ds

ref DEV-2073

## Preview

<img width="962" alt="image" src="https://github.com/user-attachments/assets/6764096b-e125-4edb-9f0a-bc4cdac13ab4">

2024-09-25 11:32 UTC, louischan-oursky requested changes

2024-09-25 11:32 UTC, louischan-oursky commented on resources/authgear/templates/en/translation.json
> +  "v2.page.page-not-found.default.title": "Page not found",
Generate translations.

2024-09-25 13:56 UTC, pkong-ds commented
Updated, thanks!

2024-09-26 04:21 UTC, louischan-oursky approved these changes

2024-09-26 04:21 UTC, merged