[WIP] Deduce sms provider config from env
authgear/authgear-server pull request #4780
Opened 2024-09-27 11:31 UTC by chankiyu22

2024-10-02 05:51 UTC, louischan-oursky requested changes

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway.go
> +package config
The convention is to name this file `sms_gateway_env.go`. For example, `redis_env.go`.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway.go
> +	Default *SMSGatewayDefaultConfig           `envconfig:"DEFAULT"`
The convention of env config struct is do not use pointers.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway.go
> +	Timeout *DurationSeconds `envconfig:"TIMEOUT"`
The convention of env config struct is do not use pointers.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway.go
> +type SMSGatewayTwilioCredentials struct {
Change the prefix of alls struct in this file to `SMSGatewayEnvironment`, for example, `SMSGatewayEnvironmentTwilioCredentials`

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/config/messaging.go
> +	SMSGateway       *SMSGateway                `json:"sms_gateway,omitempty" nullable:"true"`
Rename the struct to `SMSGatewayConfig`, to stick with the naming convention.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/infra/sms/config_resolver.go
> +	AuthgearSecretsYAMLSMSGateway  *config.SMSGateway
The name is confusing. Do you mean `AuthgearYAMLSMSProvider`, `AuthgearYAMLSMSGateway`?

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/infra/sms/config_resolver.go
> +) interface{} {
The signature is not type-strong. Can you use generics here?

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/infra/sms/provider_resolver_test.go
> +			AuthgearSecretsYAML  interface{} `yaml:"authgear.secrets.yaml"`
The testcase should take `authgear.yaml`, `authgear.secrets.yaml`, and `environment_variables`.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/infra/sms/config_resolver.go
> +package sms
I suggest we have client_resolver.go only. You unify config_resolver and provider_resolver and make them client_resolver.

2024-10-02 05:51 UTC, louischan-oursky commented on pkg/lib/infra/sms/client.go
> +	ProviderResolver             *ProviderResolver
1. Remove TwilioClient, NexmoClient, CustomClient in this struct
2. Remove NewTwilioClient, NewNexmoClient, NewCustomClient from the deps.
3. Inject ClientResolver here.
4. Use ClientResolver to resolve a client to use.
5. The API of ClientResolver is `func ResolveClient() (RawClient, error)`

2024-10-02 09:58 UTC, chankiyu22 commented
@louischan-oursky Updated.

2024-10-03 04:37 UTC, louischan-oursky requested changes

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway_env.go
> +type SMSGatewayEnvironmentUseConfigFrom string
Add type SMSGatewayEnvironmentDefaultProvider string

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/config/sms_gateway_env.go
> +type SMSGatewayEnvironmentUseConfigFrom string
Rename SMSGatewayEnvironmentUseConfigFrom to SMSGatewayEnvironmentDefaultUseConfigFrom

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +	EnvironmentDefaultProvider      config.SMSProvider
Use the new type `config.SMSGatewayEnvironmentDefaultProvider`

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +func ProvideClientResolver(
Remove this

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +		// Use `messaging.sms_provider` from `authgear.secrets.yaml`. Read config from `sms.{messaging.sms_provider}` from `authgear.secrets.yaml`
`authgear.yaml`

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +		// `provider` will be determined from application logic. Read config from `sms.{provider}` from `authgear.secrets.yaml`
`authgear.yaml`

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +		// `provider` will be determined from application logic. Read config from `sms.{provider}` from `authgear.secrets.yaml`
`authgear.yaml`

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +		// Use provider configs from `authgear.secrets.yaml`. Will read config from `sms.{sms_gateway.provider}` from `authgear.secrets.yaml`
`authgear.yaml`

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +func (r *ClientResolver) resolveConfigFromAuthgearSecretsYAML() (*NexmoClient, *NexmoClientCredentials, *TwilioClient, *TwilioClientCredentials, *CustomClient, *CustomClientCredentials) {
FromAuthgearYAMLAndAuthgearSecretsYAML

2024-10-03 04:37 UTC, louischan-oursky commented on pkg/lib/infra/sms/client_resolver.go
> +		// Use provider configs from `authgear.secrets.yaml`. Will read config from `sms.{sms_gateway.provider}` from `authgear.secrets.yaml`
`authgear.yaml`

2024-10-03 07:24 UTC, chankiyu22 commented
@louischan-oursky updated

2024-10-03 10:09 UTC, louischan-oursky approved these changes

2024-10-03 10:41 UTC, merged