[Settings v2] Delete MFA - TOTP, OTP, Password
authgear/authgear-server pull request #4792
Opened 2024-10-03 09:39 UTC by IniZio

ref DEV-1964
ref DEV-1967
ref DEV-1971
ref DEV-1961

Dependencies:
- [ ] https://github.com/authgear/authgear-server/pull/4790

Demo:

**TOTP**

https://github.com/user-attachments/assets/b4c46e9d-1fd4-414c-a0b7-6b3e9627c382

**Email**

https://github.com/user-attachments/assets/bf1d6ed9-0c2a-47e0-bb3f-d48e1b5a5b00

**OTP**

https://github.com/user-attachments/assets/20333273-8f2d-4802-ba2c-5c297ea30b9c

**Password**

https://github.com/user-attachments/assets/1c37aeaf-cf92-486b-8ca1-6f846c1f1f18

2024-10-07 07:54 UTC, louischan-oursky commented
Please rebase.

2024-10-07 08:08 UTC, louischan-oursky requested changes

2024-10-07 08:08 UTC, louischan-oursky commented on resources/authgear/templates/de/translation.json
> +  "remove-biometric-button-label": "Trennen",
Do not modify v1 translation key

2024-10-07 09:06 UTC, louischan-oursky commented
lint failed.

2024-10-07 10:34 UTC, louischan-oursky requested changes
1. Remove 2FA authenticator button has no response.
2. Add more than 1 2FA authenticator should not (re-generate recovery code and show).
3. With `authentication.recovery_code.list_enabled=true`, no recovery code related settings is shown.

2024-10-09 03:35 UTC, IniZio commented
@louischan-oursky Fixed 1 and 2, but for 3 seems some design is actually missing for regenerating recovery code. 

Asking designer for layout of regenerate action, maybe I handle it in DEV-2006 instead?

2024-10-14 03:03 UTC, louischan-oursky approved these changes

2024-10-14 03:03 UTC, merged