Display corresponding 2fa channel in text according to config
authgear/authgear-server pull request #4863
Opened 2024-10-25 10:43 UTC by tung2744

ref DEV-2146

2024-10-25 10:50 UTC, tung2744 commented on resources/authgear/templates/pl/translation.json
> -  "v2.page.settings-oob-otp.default.oob-otp-sms-button-label": "+ Dodaj numer telefonu {PhoneOTPMode, select, whatsapp {WhatsApp} whatsapp_sms {WhatsApp/SMS} other {SMS} } Passkey",
I guess this Passkey is incorrect so I removed it, although I don't know this language

2024-10-28 05:41 UTC, louischan-oursky commented
build failed.

2024-10-28 07:10 UTC, louischan-oursky approved these changes

2024-10-28 07:12 UTC, louischan-oursky requested changes

2024-10-28 07:12 UTC, louischan-oursky commented on resources/authgear/templates/en/translation.json
> +  "v2.page.settings-mfa.default.secondary-oob-otp-sms-label": "{PhoneOTPMode, select, whatsapp {WhatsApp} whatsapp_sms {WhatsApp/SMS} other {SMS} } message",
I have another thought. I think we should split this into three keys

```
v2.page.settings-mfa.default.secondary-oob-otp-sms-label--whatsapp
v2.page.settings-mfa.default.secondary-oob-otp-sms-label--sms
v2.page.settings-mfa.default.secondary-oob-otp-sms-label--whatsapp-or-sms
```

2024-10-28 08:26 UTC, tung2744 commented
Updated to separate into 3 translations

2024-10-29 06:39 UTC, tung2744 commented
Also handled dev-2250

2024-10-29 07:03 UTC, louischan-oursky approved these changes

2024-10-29 07:05 UTC, merged