Trim whitespaces in email and username normalizer
authgear/authgear-server pull request #4873
Opened 2024-10-30 08:38 UTC by tung2744

ref DEV-2253

- We did validate emails, but mail.ParseAddress is success when the email containing a space.

2024-10-31 03:37 UTC, tung2744 commented
Marked as do not merge because there are some users in production having whitespaces and will conflict with existing user if we remove those white spaces.

2024-11-08 03:06 UTC, louischan-oursky requested changes

2024-11-08 03:06 UTC, louischan-oursky commented on pkg/lib/authn/identity/loginid/checker.go
> +func (c *Checker) ValidateOne(loginID identity.LoginIDSpec, options CheckerOptions) (identity.LoginIDSpec, error) {
Having side effects (changing spec.Value) is not good in a function named ValidateOne. Validation normally should be pure. I have the following suggestions

1. Forbid constructing LoginIDSpec directly. Must use NewLoginIDSpec. NewLoginIDSpec calls strings.TrimSpace.
2. Changing the type of LoginIDSpec.Value to UserInputString. This is a safer option, as the compiler will complain on every existing call sites. Existing places have to be modified to `spec.Value.TrimSpace()` to get a safe string to use.

```
type UserInputString struct {
  UnsafeString string
}

func (s UserInputString) TrimSpace() string {
  return strings.TrimSpace(s.UnsafeString)
}

type LoginIDSpec struct {
  Key string
  Type model.LoginIDKey
  Value UserInputString 
}
```

Finally, I think UserInputString can be placed in `pkg/util/userinpututil/string.go`

2024-11-08 08:37 UTC, tung2744 commented
Updated, thanks!

2024-11-28 07:08 UTC, louischan-oursky approved these changes

2024-11-28 07:08 UTC, merged